[tool.poetry]
name = "nbaquant"
version = "0.1.0"
description = ""
authors = ["Sharif Haason <sharif.haason@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
pandas = "^2.2.2"
openpyxl = "^3.1.5"
python-dotenv = "^1.0.1"
ipykernel = "^6.29.5"
beautifulsoup4 = "^4.12.3"
nbstripout = "^0.7.1"
matplotlib = "^3.9.1"
seaborn = "^0.13.2"
numpy = "^2.0.1"
scipy = "^1.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
